apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster # Target all remote clusters (not the management cluster itself)
  template:
    metadata:
      name: '{{name}}-cilium'
    spec:
      project: default
      source:
        targetRevision: 1.12.2
        repoURL: https://helm.cilium.io
        chart: cilium
        helm:
          values: |
            hubble:
              enabled: true
              relay:
                enabled: true
              ui:
                enabled: true
            rollOutPods: true
            policyEnforcementMode: "none"
            rollOutCiliumPods: true
            priorityClassName: "system-node-critical"
            annotateK8sNode: true
            ingressController:
              enabled: true
            l7Proxy: false
            operator:
              replicas: 1
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
